baseURL: "https://rahriver.github.io/"
languageCode: "en-us"
title: "rahriver"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: 📰 Blog
      title: Blog posts
      url: /posts
      weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  description: rahriver
  # staticPath: ""  # The path to serve the static files from
  favicon: "/dna.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: false
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "rahriver" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Home
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ramin."
    subtitle: "Molecular Biology Undergrad."
    content: "A passionate Bioinformatics researcher."
    image: /images/head.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "🖋️ My C.V."
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://www.github.com/rahriver/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ramin-yousefpour
        - icon: fab fa-google
          url: mailto:ramin.y.shahrivar@gmail.com

  # About
  about:
    enable: true
    title: "🧬 About Me"
    image: "/images/about_me.jpg"
    content: |-
      I am a Bioinformatics researcher.
    skills:
      enable: true
      title: "Here are a few technologies that I've been working with recently:"
      items:
        - "Python (scikit-learn, PyTorch, NumPy, Pandas, BioPython, Matplotlib, PyQt5, OpenCV)"
        - "R (Shiny, DESeq2, GOEnrich, ggplot2)"
        - "ML (Supervised, Unsupervised)"
        - "DL (Neural Networks)"
        - "Shell Scripting"
        - "Linux"
        - "Git"
        - "LaTeX"
        - "Vim"

  # Experience
  # experience:
  #   enable: true
  #   title: "Work Experiences"
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Junior Software Developer"
  #       company: "Apple"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2020 - Aug 2020"
  #       info:
  #         enable: false
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    title: "🎓 Education"
    index: false
    items:
      - title: "Bachelor of Science in Cell and Molecular Biology"
        school:
          name: "Department of Biology, College of Convergent Sciences and Technologies, Science and Research Branch, Islamic Azad University, Tehran, Iran"
          # url: "https://example.org"
        date: "2020 - Present"
        GPA: "3.9/4.0."
 #        content: |-
 #          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
 #          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
 #          - Face mask detection using a single convolutional neural network.

# 
 #          Extracurricular Activities
 #            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
 #            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "Transcript of Grades"
          url: "https://example.com"

      - title: "💬 TOEFL iBT Test"
        school:
          name: "Score: 102/120"
          # url: "https://example.org"
        date: "July 2023"
        # GPA: "102/120"

  # Publications
  achievements:
    enable: true
    title: "📄 Publications"
    items:
      - title: "Smart Lipid-Based Nanoparticles in Lung Cancer Treatment: Current Status and Future Directions"
        content: Under Review | Wiley's Advanced Therapeutics (IF=5, Q1) | 2023
        # url: https://example.com
        image: /images/publications/smart.png
        
      - title: "Enhancing Fetal Anomaly Detection in Ultrasound Images: A Review of Machine Learning-Based Approaches"
        content: Invited Review | MDPI Biomimetics (IF=4.5, Q2) | 2023
        image: /images/publications/fetal.jpg
        
      - title: "Comprehensive Analysis of Tay-Sachs and Niemann-Pick Disease: Shared and Distinct Genes and Pathways"
        content: Invited | MDPI Information (IF=3.1, Q2) | 2023
        # url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/publications/tay.jpg
        
      - title: "Detection of Major Structural Chromosomal Abnormalities in Human Karyotypes using Convolutional Neural Networks"
        content: Presented | 1st International Congress of Artificial Intelligence in Medical Sciences | Presenter | 2023
        image: /images/publications/cnn.png

      - title: "A Systematic Review on the Potential of Circulatory Cell-Free DNA in the Diagnosis of Systemic Lupus Erythematosus Patient"
        content: Presented | 16th International Congress of Immunology and Allergy | Presenter | 2023
        # url: https://example.com
        image: /images/publications/systemic.png

  projects:
    enable: true
    title: "⚙️ Projects"
    items:
      - title: Primer X
        content: A workspace to perform quality analysis on primers using the Primer3 and Shiny libraries
        image: /images/projects/primerx.png
        featured:
          name: Repo
          link: https://www.github.com/rahriver/primerx
        badges:
          - "R"
          - "Primer 3"
          - "Shiny"

      - title: Rofi Noter
        content: A bash script that facilitates seamless management of notes for users.
        image: /images/projects/rofi.png
        featured:
          name: Repo
          link: https://github.com/rahriver/rofi-noter
        badges:
          - "Shell"
          - "Linux"

      - title: Arch Linux for Scientists
        content: Configuration and bootstrap for arch Linux, aimed at scientists and researchers who use Linux as their primary operating system
        image: /images/projects/arch.png
        featured:
          name: Repo
          link: https://github.com/rahriver/Arch-Linux
        badges:
          - "Linux"
          - "Shell"
          - "Python"
          - "Vim Script"

      - title: <Genome/X>
        content: GUI user interface for Biopython and other bioinformatics related Python packages.
        image: /images/projects/genomex.png
        featured:
          name: Repo
          link: https://github.com/rahriver/Genome-X
        badges:
          - "Python"
          - "Biopython"
          - "PyQT5"
        links:
          - icon: fab fa-telegram
          - url: google.com

  #Contact
  contact:
    enable: true
    title: "📞 Contact"
    # content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ramin.y.shahrivar@gmail.com
    btnName: "📩 Mail me"
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/rahriver/
      linkedin: https://linkedin.com/in/ramin-yousefpour

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
