baseURL: "https://rahriver.github.io/"
languageCode: "en-us"
title: "rahriver"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: 📰 Blog
      title: Blog posts
      url: /posts
      weight: 1
    # - identifier: gallery
    #   name: 🎨 Gallery
    #   title: Gallery
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Menu
    #   name: 🟰 Other
    #   weight: 3
    # - identifier: dropdown1
    #   title: 📬 Posts
    #   name: 📬 Posts
    #   url: /posts
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: 🎨 Gallery
    #   name: 🎨 Gallery
    #   url: /gallery
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  description: rahriver
  # staticPath: ""  # The path to serve the static files
  favicon: "/dna.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  # Make nav bar sticky
  stickyNav: false

  theme:
    # disableThemeToggle: false
    defaultTheme: "light" # dark, light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "rahriver" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Home
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ramin."
    subtitle: "Computational Biology, Bioinformatics, Genomics"
    content: "I'm a passionate FOSS (Free and Open Source Software) enthusiast, and I love using and developing open-source tools for analyzing biological data."
    image: /images/head.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "My CV"
      url: "https://drive.google.com/file/d/1lNPsyrigvvmAwvJwp9cMN0Yq-tNlGQJW/view?usp=sharing"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://www.github.com/rahriver/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ramin-yousefpour
        - icon: fab fa-google
          url: mailto:ramin.y.shahrivar@gmail.com

  # About
  about:
    enable: true
    title: "</> About Me"
    image: "/images/me2.jpg"
    # content: |-
      # Bioinformatics researcher.
    skills:
      enable: true
      title: "Here are a few technologies that I work with:"
      items:
        - "Python (scikit-learn, PyTorch, BioPython, PyQt5)"
        - "R (DESeq2, GOEnrich, WGCNA, ggplot2)"
        - "Machine Learning"
        - "Deep Learning (CNN)"
        - "Shell"
        - "Linux"
        - "Git"
        - "LaTeX"
        - "NeoVim"

# Experiences
  experience:
    enable: true
    title: "🔬 Research Experiences"
    items:
      - job: "Research Assistant"
        company: "Shiraz University of Medical Sciences"
        # companyUrl: "https://example.com"
        date: "2023 - Present"
        featuredLink:
          enable: true
          name: "Webpage"
          url: "https://gsia.sums.ac.ir/"
        content: "Computational research on developing wound dressing for Epidermolysis Bullosa patients. Techniques used: Spatial transcriptomics, RNA-seq data analysis. Supervisor: Dr. Mahsa Sani"
      - job: "Research Assistant"
        company: "Islamic Azad University Science and Research Branch"
        # companyUrl: "https://example.com"
        date: "2022 - Present"
        featuredLink:
          enable: true
          name: "Webpage"
          url: "https://srb.iau.ir/en"
        content: "Conducting computational research on differentially expressed genes in human disorders using various programming and bioinformatics tools. Developing machine learning models for medical image analysis (MRI, Ultrasonography). Writing literature review papers on research topics. Supervisor: Dr. Fatemeh Karami"
      - job: "Scientific Writer"
        company: "Rouyesh Magazine"
        # companyUrl: "https://example.com"
        date: "2022 - Present"
        featuredLink:
          enable: true
          name: "Recent Volume"
          url: "https://drive.google.com/file/d/1O4gBNCf6WiKf-WwLADGsMI0e77RZrf1y/view?usp=sharing"
        content: "Editorial board member at the Rouyesh scientific magazine. This position involves writing scientific articles across a wide range of subjects to captivate both academic and non-academic audiences."

  # Education
  education:
    enable: true
    title: "🎓 Education"
    index: false
    items:
      - title: "Bachelor of Science in Cell and Molecular Biology"
        school:
          name: "Department of Biology, College of Convergent Sciences and Technologies, Science and Research Branch, Islamic Azad University, Tehran, Iran"
          url: "https://www.usnews.com/education/best-global-universities/islamic-azad-university-528829"
        date: "2020 - Present"
        GPA: "3.9/4.0"
 #        content: |-
        featuredLink:
          enable: true
          name: "Transcript of Grades"
          url: "https://drive.google.com/file/d/1sBwCxYOzPZutZtleYynClRg6AKEtw9ct/view?usp=sharing"
          download: true
          newPage: true

      - title: "💬 TOEFL iBT Test"
        school:
          name: "Score: 102/120"
          # url: "https://example.org"
        date: "9/July/2023"
        # GPA: "102/120"

  # Publications
  achievements:
    enable: true
    title: "📄 Publications"
    items:
      - title: "Smart Lipid-Based Nanoparticles in Lung Cancer Treatment: Current Status and Future Directions"
        content: Published | Wiley's Advanced Therapeutics (IF=4.74, Q1) | 2023
        url: https://onlinelibrary.wiley.com/doi/abs/10.1002/adtp.202300275
        image: /images/publications/smartNP.png
        
      - title: "Enhancing Fetal Anomaly Detection in Ultrasonography Images: A Review of Machine Learning-Based Approaches"
        content: Published | MDPI Biomimetics (IF=4.5, Q2) | 2023
        url: https://www.mdpi.com/2313-7673/8/7/519/htm
        image: /images/publications/fetal.png
        
      - title: "CRISPR-mediated Genome Engineering: Breakthroughs and Challanges"
        content: Under Review | Transgenic Research (IF=3.14, Q2) | 2023
        # url: /posts/abs_crispr
        image: /images/publications/crispr.png

      - title: "Comprehensive Analysis of Tay-Sachs and Niemann-Pick Disease: Shared and Distinct Genes and Pathways"
        content: To be submitted | PLoS Computational Biology (IF=4.7, Q1) | 2023
        # url: 
        image: /images/publications/tay.jpg
        
      - title: "Detection of Major Structural Chromosomal Abnormalities in Human Karyotypes using Convolutional Neural Networks"
        content: Presented | 1st International Congress of Artificial Intelligence in Medical Sciences | Presenter | 2023
        url: /posts/abs_aims
        image: /images/publications/cnn.png

      - title: "A Systematic Review on the Potential of Circulatory Cell-Free DNA in the Diagnosis of Systemic Lupus Erythematosus Patient"
        content: Presented | 16th International Congress of Immunology and Allergy | Presenter | 2023
        url: /posts/abs_sle
        image: /images/publications/systemic.png

  projects:
    enable: true
    title: "⚙️ Projects"
    items:

      - title: Arch Linux for Scientists
        content: Configuration and bootstrap for Arch Linux, customized for scientists and researchers who use Linux as their primary operating system
        image: /images/projects/archlinux.png
        featured:
          name: GitHub
          link: https://www.github.com/rahriver/Arch-Linux
        badges:
          - "61 ⭐"
          - "Linux"
          - "Shell"
          - "Python"
        links:
          - icon: fab fa-linux
          - url: "https://www.itsfoss.com/best-window-managers"

      - title: Rofi Noter
        content: A bash script that facilitates seamless management of notes on Linux.
        image: /images/projects/rofi-noter.png
        featured:
          name: GitHub
          link: https://www.github.com/rahriver/rofi-noter
        badges:
          - "24 ⭐"
          - "Shell"
          - "Linux"
        # links:
        #   - icon: fab fa-reddit
        #   - url: "https://www.reddit.com/r/unixporn/comments/11fzd37/rofi_notetaking_manager/"

      - title: Primer X
        content: R-Shiny interface to perform primer quality analysis using the Primer3 library.
        image: /images/projects/primerx.png
        featured:
          name: GitHub
          link: https://www.github.com/rahriver/primerx
        badges:
          - "R"
          - "Primer 3"
          - "Shiny"

      - title: <Genome/X>
        content: GUI user interface for Biopython and other bioinformatics related Python packages.
        image: /images/projects/genomex.png
        featured:
          name: GitHub
          link: https://www.github.com/rahriver/Genome-X
        badges:
          - "Python"
          - "Biopython"
          - "PyQT5"

      - title: Academ.AI
        content: This Python script is designed to scrape Google Scholar, allowing users to extract research titles and abstracts from any scholar's profile. It also has the capability to generate graphs that visualize the similarities between these research titles
        image: /images/projects/academai.png
        featured:
          name: GitHub
          link: https://www.github.com/rahriver/Academ.AI
        badges:
          - "Python"
          - "beautifulsoup"
          - "Universal sentence encoder"
          - "Spacy"

      - title: Ankinator
        content: Extract new words from text files, and create Anki flash cards out of them.
        image: /images/projects/anki.png
        featured:
          name: GitHub
          link: https://www.github.com/rahriver/Ankinator
        badges:
          - "8 ⭐"
          - "Python"
          - "Anki"

  #Contact
  contact:
    enable: false
    title: "📞 Contact"
    # content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: ramin.y.shahrivar@gmail.com
    btnName: "📩 Email me"
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "posts"
      count: 2
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/rahriver/
      linkedin: https://linkedin.com/in/ramin-yousefpour

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Oops not found!"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
